board/urls.py
from django.urls import path

from board import views

app_name = 'board'

urlpatterns = [
    path('<int:hid>/agenda', views.CalendarView.as_view(), name='board'),
    path('<int:hid>/agenda/occupancies.json', views.occupancies_json_view, name='occupancies-json'),
    path('<int:hid>/agenda/reservations.json', views.ReservationsJsonView.as_view(), name='reservations-json'),
    path('<int:hid>/reservation/new', views.ReservationCreateRequestView.as_view(), name='create-reservation'),
    path(
        '<int:hid>/reservation/new/calculate', views.ReservationCalculateView.as_view(), name='calculate-reservation'
    ),
    path('<int:hid>/reservation/new/save', views.ReservationCreateView.as_view(), name='save-reservation'),
    path('<int:hid>/reservation/close', views.RoomCloseCreateView.as_view(), name='create-close'),
    path('<int:hid>/reservation/close/update', views.RoomCloseUpdateView.as_view(), name='update-close'),
    path('<int:hid>/reservation/close/delete', views.RoomCLoseDeleteView.as_view(), name='delete-close'),
    path('<int:hid>/reservation/move', views.ReservationMoveView.as_view(), name='move-reservation'),
    path('<int:hid>/reservation/<int:pk>/details', views.ReservationDetailsView.as_view(), name='reservation'),
    path('<int:hid>/reservation/<int:pk>/accept', views.ReservationAcceptView.as_view(), name='accept-reservation'),
    path('<int:hid>/reservation/<int:pk>/cancel', views.ReservationCancelView.as_view(), name='cancel-reservation'),
    path('<int:hid>/reservation/<int:pk>/verify', views.VerifyFormView.as_view(), name='verify-changes'),
    path('<int:hid>/reservation/<int:pk>/verify/save', views.VerifyFormSaveView.as_view(), name='accept-changes'),
    path('<int:hid>/reservation/<int:pk>/<int:rid>/prices', views.UpdatePricesFormView.as_view(), name='show-prices'),
    path(
        '<int:hid>/reservation/<int:pk>/<int:rid>/prices/save',
        views.UpdatePricesFormSaveView.as_view(),
        name='save-prices',
    ),
]

board/views/_calendar_view.py
from typing import Any, Dict, List, TYPE_CHECKING, Tuple

from django import http
from django.http import Http404
from django.views.generic import TemplateView

from board.permissions import Permissions
from board.usecases import ShowCalendar
from board.value_objects import CalendarErrors
from common import functions as cf
from common.http import RenderServerError
from common.loggers import Logger
from common.mixins import AjaxServiceMixin
from effective_tours.constants import RoomCloseReasons
from houses.permissions import Permissions as HousePermissions

if TYPE_CHECKING:
    from board.value_objects import CalendarContext
    from common.value_objects import CaseError
    from houses.entities import Room, RoomTypeDetails


class CalendarView(AjaxServiceMixin, TemplateView):
    http_method_names = ['get']
    permissions = [
        Permissions.BOARD_READ,
        HousePermissions.HOUSE_READ,
        HousePermissions.ROOMTYPE_READ,
        HousePermissions.ROOM_READ,
    ]
    template_name = 'board/calendar.html'

    def get(self, request: http.HttpRequest, *args: Any, **kwargs: Any) -> http.HttpResponse:
        start_date = cf.get_date_or_none(request.GET.get('sd'))  # noqa
        return self.process_usecase(ShowCalendar, self.kwargs['hid'], start_date, user=request.user)

    def render_success(self, ctx: 'CalendarContext' = None, **kwargs) -> http.HttpResponse:
        return self.render_to_response(self.get_context_data(ctx=ctx))

    def render_failure(self, failure: 'CaseError', **kwargs) -> http.HttpResponse:
        Logger.warning(__name__, str(failure))
        if failure.failure == CalendarErrors.missed_house:
            raise Http404(failure.error)
        return RenderServerError(request=self.request).do()

    def get_context_data(self, ctx: 'CalendarContext' = None, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context.update(ctx.asdict())
        context['house'] = context['CURRENT_HOUSE'] = ctx.house
        context['structure'] = self.prepare_structure(ctx.room_types, ctx.rooms)
        context['close_reasons'] = RoomCloseReasons.choices()
        try:
            context['close_rooms'] = self.prepare_close_rooms(ctx.rooms, ctx.room_types)
        except Exception as err:
            Logger.warning(__name__, f"Error select Rooms for House ID={ctx.house.id} : {err}")
        return context

    @staticmethod
    def prepare_structure(room_types: List["RoomTypeDetails"], rooms: List["Room"]) -> List[Dict[str, Any]]:
        result = []
        for room_type in room_types:
            result.append(
                {
                    'name': room_type.name,
                    'room_type': room_type,
                    'rooms': [x for x in rooms if x.roomtype_id == room_type.id],
                }
            )
        return result

    @staticmethod
    def prepare_close_rooms(rooms: List["Room"], room_types: List["RoomTypeDetails"]) -> List[Tuple[int, str]]:
        _room_types = {x.id: x for x in room_types}
        result = []
        for room in rooms:
            if room.roomtype_id in _room_types:
                name = f"{room.name} / {_room_types[room.roomtype_id].name}"
            else:
                name = room.name
            result.append((room.id, name))
        return sorted(result, key=lambda x: x[1])

board/views/_reservation_details_view.py
import datetime
from typing import Any, Dict, List, TYPE_CHECKING

from django import http
from django.views.generic import TemplateView

from board.permissions import Permissions
from board.usecases import SelectReservation
from board.value_objects import ReservationErrors
from common import functions as cf
from common.http import RenderServerError
from common.loggers import Logger
from common.mixins import AjaxServiceMixin

if TYPE_CHECKING:
    from board.entities import Reservation
    from board.value_objects import ReservationDetailsContext
    from common.value_objects import CaseError


class ReservationDetailsView(AjaxServiceMixin, TemplateView):
    http_method_names = ['get']
    permissions = [Permissions.RESERVATION_READ]
    template_name = 'board/reservation_details.html'

    def get(self, request: http.HttpRequest, *args: Any, **kwargs: Any) -> http.HttpResponse:
        return self.process_usecase(SelectReservation, self.kwargs['hid'], self.kwargs['pk'], request.user)

    def render_success(self, ctx: 'ReservationDetailsContext' = None, **kwargs) -> http.HttpResponse:
        return self.render_to_response(self.get_context_data(ctx=ctx))

    def render_failure(self, failure: 'CaseError', **kwargs) -> http.HttpResponse:
        Logger.warning(__name__, str(failure))
        if failure.failure in (ReservationErrors.missed_house, ReservationErrors.missed_reservation):
            raise http.Http404(failure.error)
        return RenderServerError(request=self.request).do()

    def get_context_data(self, ctx: 'ReservationDetailsContext' = None, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context.update(ctx.asdict())
        context['CURRENT_HOUSE'] = ctx.house
        context['reservation_rooms'] = self.prepare_rooms(ctx.reservation)
        context['guest_id'] = cf.get_int_or_none(self.request.GET.get('guest_id'))  # noqa
        context['pending_balance'] = ctx.reservation.price_accepted - ctx.payed_amount
        return context

    @staticmethod
    def prepare_rooms(reservation: 'Reservation') -> List[Dict[str, Any]]:
        result = []
        for room in reservation.rooms:
            data = {'room': room, 'periods': []}
            period = {'start_date': None, 'end_date': None, 'room_type': None, 'room': None}
            for price in sorted(room.day_prices, key=lambda x: x.day):
                period['end_date'] = price.day + datetime.timedelta(days=1)
                if period['start_date'] is None:
                    period['start_date'] = price.day

                if period['room_type'] is None:
                    period['room_type'] = price.room_type
                    period['room'] = price.room
                elif period['room_type'] != price.room_type:
                    period['end_date'] = price.day
                    data['periods'].append(period)
                    period = {
                        'start_date': price.day,
                        'end_date': price.day + datetime.timedelta(days=1),
                        'room_type': price.room_type,
                        'room': price.room,
                    }
                elif period['room'] is None and price.room is not None:
                    period['end_date'] = price.day
                    data['periods'].append(period)
                    period = {
                        'start_date': price.day,
                        'end_date': price.day + datetime.timedelta(days=1),
                        'room_type': price.room_type,
                        'room': price.room,
                    }
                elif period['room'] != price.room:
                    period['end_date'] = price.day
                    data['periods'].append(period)
                    period = {
                        'start_date': price.day,
                        'end_date': price.day + datetime.timedelta(days=1),
                        'room_type': price.room_type,
                        'room': price.room,
                    }
            if period['start_date'] is not None:
                data['periods'].append(period)
            result.append(data)
        return result

board/templates/board/details_tab_main.html
{% load et_i18n ledger_tags members_tags %}
<div class="row">
  <div class="col-12 col-sm-6 col-md-7 col-lg-8 col-xl-9">

    {% ifperms user PERMISSIONS.board.RESERVATION_UPDATE house %}
      <div class="mb-3">
        {% if not reservation.is_verified and reservation.is_ota %}
          <button class="btn btn-outline-warning" onclick="AgendaJS.showVerifyForm('#id_verify_modal', '{% url "board:verify-changes" hid=house.id pk=reservation.id %}')">{% trans "agenda:btn:verify" %}</button>
        {% endif %}
        {% if reservation.status.name == "HOLD" %}
          <button class="btn btn-outline-success" onclick="AgendaJS.acceptReservation()">{% trans "agenda:btn:accept" %}</button>
        {% endif %}
        <button class="btn btn-outline-secondary" disabled>{% trans "agenda:btn:checkedin" %}</button>
        <button class="btn btn-outline-secondary" disabled>{% trans "agenda:btn:noshow" %}</button>
      </div>
    {% endifperms %}

    <div class="mb-2">
      <span class="text-nowrap mr-2">
        <strong>{% trans "agenda:client:label" %}:</strong> {{ reservation.get_guest_name }}
      </span>
      {% if reservation.guest_email or reservation.guest_phone %}
        <span class="text-nowrap">
          {% if reservation.guest_email %}
            <span class="text-nowrap mr-2">
              <a href="mailto:{{ reservation.guest_email }}">{{ reservation.guest_email }}</a>
            </span>
          {% endif %}
          {% if reservation.guest_phone %}
            <span class="text-nowrap">
              <i class="fas fa-fw fa-phone"></i> {{ reservation.guest_phone }}
            </span>
          {% endif %}
        </span>
      {% endif %}
    </div>
    <div class="mb-2">
      <span class="text-nowrap mr-2">
        <strong>{% trans "agenda:checkin:label" %}:</strong> {{ reservation.get_checkin_time|date:"d.M.Y H:i" }}
      </span>
      <span class="text-nowrap mr-2">
        <strong>{% trans "agenda:checkout:label" %}:</strong> {{ reservation.get_checkout_time|date:"d.M.Y H:i" }}
      </span>
      <span class="text-nowrap">
        <strong>{% trans "agenda:nights:label" %}:</strong> {{ reservation.get_nights }}
      </span>
    </div>
    <div class="mb-2">
      <span class="text-nowrap mr-2">
        <strong>{% trans "agenda:adults:label" %}:</strong> {{ reservation.get_total_adults|default:"-" }}
      </span>
      <span class="text-nowrap">
        <strong>{% trans "agenda:children:label" %}:</strong> {{ reservation.get_total_children|default:"-" }}
      </span>
    </div>
  </div>
  <div class="col-12 col-sm-6 col-md-5 col-lg-4 col-xl-3">
    <table class="table table-sm table-borderless reservation__summary">
      <tbody>
        <tr>
          <th class="text-right">{% trans "agenda:summary:price" %}</th>
          <td colspan="text-right">{{ reservation.price_accepted|money_format:house.currency }}</td>
        </tr>
        <tr>
          <th class="text-right">{% trans "agenda:summary:extra" %}</th>
          <td colspan="text-right">{{ 0|money_format:house.currency }}</td>
        </tr>
        <tr class="table-success">
          <th class="text-right">{% trans "agenda:summary:total" %}</th>
          <td colspan="text-right">{{ reservation.price_accepted|money_format:house.currency }}</td>
        </tr>
        <tr>
          <th class="text-right">{% trans "agenda:summary:payed" %}</th>
          <td colspan="text-right">{{ payed_amount|money_format:house.currency }}</td>
        </tr>
        <tr class="text-danger border-danger">
          <th class="text-right">{% trans "agenda:summary:balance" %}</th>
          <td colspan="text-right">{{ pending_balance|money_format:house.currency }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<div class="row mt-4">
  <div class="col-12">
    <div class="reservation__rooms">
      <h4 class="h4 mb-2">{% trans "agenda:page:rooms_subtitle" %}</h4>
      {% for item in reservation_rooms %}
        <div class="row mb-4">
          <div class="col-12">
            <div class="row">
              <div class="col-12">
                {% if reservation.is_ota %}
                  {{ item.room.external_name|default:"---" }}
                {% else %}
                  {% trans "agenda:page:direct_booking" %}
                {% endif %}
                &nbsp;|&nbsp;
                {{ item.room.rate_plan.name|default:"--" }}
                {% if item.room.policy %}
                  &nbsp;|&nbsp;
                  <a tabindex="0" data-toggle="popover" data-trigger="hover" title="" data-content="{{ item.room.policy.name }}" data-container="body">
                    <strong>{% trans "agenda:page:cancelation_policy" %}</strong>
                    <i class="fas fa-fw fa-coins text-warning"></i>
                  </a>
                {% endif %}
                {% if reservation.allow_update_prices %}
                  <button type="button" role="button" class="btn btn-sm btn-outline-success ml-3" onclick="AgendaJS.showPriceForm('#id_prices_modal', '{% url "board:show-prices" hid=house.id pk=reservation.id rid=item.room.id %}')">{% trans "common:btn:edit" %}</button>
                {% endif %}
              </div>
            </div>
            {% for period in item.periods %}
              <div class="row mt-2">
                <div class="col-6 col-lg-3 col-md-4 col-sm-5 pl-4">
                  - {{ period.room_type.name }} {% if period.room %} | {{ period.room.name }}{% endif %}
                </div>
                <div class="col-6 col-lg-8">
                  {{ period.start_date|date:"d.M.Y" }} &mdash; {{ period.end_date|date:"d.M.Y" }}
                </div>
              </div>
            {% endfor %}
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
</div>

<div class="row mt-4">
  <div class="col-12">
    <div class="reservation__services">
      <div class="d-flex justify-content-between mb-2">
        <h4 class="h4">{% trans "agenda:page:services_subtitle" %}</h4>
        <button type="button" class="btn btn-outline-success">{% trans "agenda:btn:services" %}</button>
      </div>
      {% for service in services %}
      {% empty %}
        <div class="alert text-muted justify-content-center" role="alert">
          {% trans "agenda:page:no_services" %}
        </div>
      {% endfor %}
    </div>
  </div>
</div>

<div class="row mt-4">
  <div class="col-12">
    <div class="reservation__source">
      <span class="text-nowrap mr-2">
        <strong>{% trans "agenda:source:label" %}:</strong>
        {% if reservation.is_ota %}
          {{ reservation.source.value }}
        {% else %}
          <span class="editable editable-click">{{ reservation.source.value }}</span>
        {% endif %}
      </span>
      {% if reservation.channel_id %}
        <span class="text-nowrap">
          <strong>{% trans "agenda:sourcenr:label" %}:</strong>
          {{ reservation.channel_id|default:'-' }}
        </span>
      {% endif %}
    </div>

  </div>
</div>

<div class="row mt-4">
  <div class="col-12">
    <h4 class="h4 mb-2">Tasks</h4>
  </div>
</div>

board/templates/board/reservation_details.html
{% extends "./__base.html" %}
{% load et_i18n members_tags %}

{% block page-title %}{% trans "agenda:page:reservation_details" %} :: {{ house.name }} :: {{ block.super }}{% endblock %}

{% block breadcrumb %}
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'dashboard:dashboard' %}">{% trans "common:home:breadcrumb" %}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'board:board' hid=house.id %}">{% trans "agenda:page:title" %}</a></li>
    <li class="breadcrumb-item active">{% trans "agenda:page:reservation_details" %}</li>
  </ol>
{% endblock breadcrumb %}

{% block page-content %}
  <div class="d-md-flex justify-content-md-between">
    <h5 class="h5 mb-3">
      <span class="reservation__guest-name">{{ reservation.get_guest_name }}</span>
      | {% trans "agenda:page:reservation_number" pk=reservation.get_id %}
      {% if reservation.status.name == "MODIFY" or reservation.status.name == "CANCEL" or reservation.status.name == "HOLD" %}
        <span class="reservation__status">[{{ reservation.status.value }}]</span>
      {% endif %}
    </h5>

    {% ifperms user PERMISSIONS.board.RESERVATION_DELETE house %}
      {% if reservation.allow_delete and reservation.status.name != "CANCEL" %}
        <button type="button" role="button" class="btn btn-danger text-uppercase mb-3" onclick="AgendaJS.cancelReservation()">
          {% trans "agenda:btn:delete_reservation" %}
        </button>
      {% endif %}
    {% endifperms %}
  </div>

  <div class="tab reservation__tabs">
    <ul class="nav nav-tabs" role="tablist">
      <li class="nav-item" role="presentation">
        <a id="main_tab" href="#tab-1" data-toggle="tab" role="tab" class="nav-link active">{% trans "agenda:tab:main" %}</a>
      </li>
      <li class="nav-item" role="presentation">
        <a id="guests_tab" href="#tab-2" data-toggle="tab" role="tab" class="nav-link">{% trans "agenda:tab:guests" %}</a>
      </li>
      <li class="nav-item" role="presentation">
        <a id="messages_tab" href="#tab-3" data-toggle="tab" role="tab" class="nav-link">{% trans "agenda:tab:messages" %}</a>
      </li>
      {% ifperms user PERMISSIONS.invoices.INVOICE_READ house %}
        <li class="nav-item" role="presentation">
          <a id="bill_tab" href="#tab-4" data-toggle="tab" role="tab" class="nav-link">{% trans "agenda:tab:bill" %}</a>
        </li>
      {% endifperms %}
      <li class="nav-item" role="presentation">
        <a id="journal_tab" href="#tab-5" data-toggle="tab" role="tab" class="nav-link">{% trans "agenda:tab:journal" %}</a>
      </li>
    </ul>
    <div class="tab-content">

      <div id="tab-1" class="tab-pane show active" role="tabpanel" aria-labelledby="main_tab">
        {% include "./details_tab_main.html" %}
      </div><!--//#tab-1 -->

      <div id="tab-2" class="tab-pane" role="tabpanel" aria-labelledby="guests_tab">
        {% include "./details_tab_guests.html" %}
      </div><!--//#tab-2 -->

      <div id="tab-3" class="tab-pane" role="tabpanel" aria-labelledby="messages_tab">

      </div><!--//#tab-3 -->

      {% ifperms user PERMISSIONS.invoices.INVOICE_READ house %}
        <div id="tab-4" class="tab-pane" role="tabpanel" aria-labelledby="bill_tab">
          {% include "./details_tab_invoices.html" %}
        </div><!--//#tab-4 -->
      {% endifperms %}

      <div id="tab-5" class="tab-pane" role="tabpanel" aria-labelledby="journal_tab">

      </div><!--//#tab-5 -->

    </div>
  </div>


  {% if not reservation.is_verified %}
    <!-- Modal for Verify Reservation -->
    <div class="modal fade" tabindex="-1" id="id_verify_modal" aria-labelledby="id_verify_modal_title" aria-hidden="true" data-backdrop="static">
      <div class="modal-dialog modal-dialog-centered modal-lg modal-dialog-scrollable">
        <div class="modal-content">
          <div class="modal-header">
            <h5 id="id_verify_modal_title" class="modal-title">{% trans "agenda:page:verify_title" %}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="{% trans 'common:btn:close' %}">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body"></div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" onclick="AgendaJS.saveVerifyForm('#id_verify_modal')">{% trans "agenda:btn:update_verify" %}</button>
          </div>
        </div>
      </div>
    </div>
  {% endif %}

  <!-- Modal for Update Reservation prices -->
  <div class="modal fade" tabindex="-1" id="id_prices_modal" aria-labelledby="id_prices_modal_title" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
      <div class="modal-content">
        <div class="modal-header">
          <h5 id="id_prices_modal_title" class="modal-title">{% trans "agenda:page:prices_modal_title" %}</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="{% trans 'common:btn:close' %}">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body"></div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" onclick="AgendaJS.savePriceForm('#id_prices_modal')">{% trans "agenda:btn:save_prices" %}</button>
        </div>
      </div>
    </div>
  </div>

  <template id="id_priceformspinner">
    <div class="text-center p-5">
      <div class="spinner-border text-dark">
        <span class="sr-only">{% trans "common:page:loading" %}</span>
      </div>
    </div>
  </template>

{% endblock page-content %}

{% block head-scripts %}
  {{ block.super }}
  <script>
    AGENDA_CONFIG.URL.CONTACT_FORM_URL = "{% url 'contacts:form-json' hid=house.id %}";
    AGENDA_CONFIG.URL.ACCEPT_URL = "{% url 'board:accept-reservation' hid=house.id pk=reservation.id %}";
    AGENDA_CONFIG.URL.CANCEL_URL = "{% url 'board:cancel-reservation' hid=house.id pk=reservation.id %}";
    AGENDA_CONFIG.URL.GUESTS_URL = "{% url 'contacts:reservation-guests' hid=house.id rid=reservation.id %}";
    AGENDA_CONFIG.URL.INVOICES_URL = "{% url 'invoices:reservation' hid=house.id rid=reservation.id %}";
    AGENDA_CONFIG.MSG.EDITABLE_PLACEHOLDER = "{% trans 'contacts:page:empty_value' %}";
    AGENDA_CONFIG.MSG.CONTACT_UPDATE_OK = "{% trans 'contacts:update:success' %}";
    AGENDA_CONFIG.MSG.ACCEPT_ASK = "{% trans 'agenda:page:accept_ask' %}";
    AGENDA_CONFIG.MSG.CANCEL_ASK = "{% trans 'agenda:page:cancel_ask' %}";
    AGENDA_CONFIG.MSG.VERIFY_SAVE_ASK = "{% trans 'agenda:page:verify_save_ask' %}";
    AGENDA_CONFIG.MSG.PRICES_SAVE_SUCCESS = "{% trans 'agenda:page:prices_save_success' %}";
    {% ifperms user PERMISSIONS.invoices.PAYMENT_DELETE house %}
      AGENDA_CONFIG.URL.CANCEL_PAYMENT_URL = "{% url 'invoices:payment-cancel' hid=house.id rid=reservation.id %}";
      AGENDA_CONFIG.MSG.CANCEL_PAYMENT_ASK = "{% trans 'invoices:page:payment_cancel_ask' %}";
    {% endifperms %}
    {% ifperms user PERMISSIONS.invoices.INVOICE_DELETE house %}
      AGENDA_CONFIG.URL.CANCEL_INVOICE_URL = "{% url 'invoices:cancel' hid=house.id rid=reservation.id %}";
      AGENDA_CONFIG.MSG.CANCEL_INVOICE_ASK = "{% trans 'invoices:page:invoice_cancel_ask' %}";
    {% endifperms %}
    AGENDA_CONFIG.MSG.INVOICE_ERR = "{% trans 'invoices:error:select_invoice' %}";
    const RESID = {{ reservation.id }};
  </script>
{% endblock head-scripts %}

{% block source-scripts %}
  {{ block.super }}
  <script>
    $(function(){
      $("[rel=tooltip]").tooltip();

      AgendaJS.loadGuests('#id_reservation_guests');
      {% ifperms user PERMISSIONS.invoices.INVOICE_READ house %}
        AgendaJS.loadInvoices('#id_reservation_invoices');
      {% endifperms %}
      {% if guest_id %}
        AgendaJS.loadContactForm('#id_guest_details', {{ guest_id }}, {% if reservation.is_ota and guest_id == reservation.guest_contact_id %}1{% else %}0{% endif %});
      {% elif reservation.guest_contact_id %}
        AgendaJS.loadContactForm('#id_guest_details', {{ reservation.guest_contact_id }}, {% if reservation.is_ota %}1{% else %}0{% endif %});
      {% endif %}

      if (window.location.hash === "#tab-2") {
        $(".reservation__tabs li:nth-child(2) a").tab("show");
      }
    });
  </script>
{% endblock source-scripts %}

board/templates/board/verify_form.html
{% load et_i18n ledger_tags %}
<div class="container-fluid">
  <form action="{% url 'board:accept-changes' hid=house.id pk=reservation.id %}" method="post" onsubmit="return false">
    {% csrf_token %}
    {% for room in reservation.rooms %}
      <div class="row">
        <div class="col">
          <div class="row">
            <div class="col-md-3"><strong>{% trans "agenda:page:room_rate" %}</strong></div>
            <div class="col">{{ room.rate_plan.name|default:'---' }}</div>
            <div class="col-md-1">
              <i class="align-middle fas fa-fw fa-long-arrow-alt-right"></i>
            </div>
            <div class="col">{{ room.rate_plan_original.name|default:'---' }}</div>
          </div>
          <div class="row">
            <div class="col-md-3"><strong>{% trans "agenda:page:room_period" %}</strong></div>
            <div class="col">{{ room.checkin|date:'d.M.Y' }} - {{ room.checkout|date:'d.M.Y' }}</div>
            <div class="col-md-1">
              <i class="align-middle fas fa-fw fa-long-arrow-alt-right"></i>
            </div>
            <div class="col">{{ room.checkin_original|date:'d.M.Y' }} - {{ room.checkout_original|date:'d.M.Y' }}</div>
          </div>
        </div>

        <table class="table table-sm table-striped mt-3">
          <thead>

            <tr>
              <th>{% trans "agenda:th:date" %}</th>
              <th>{% trans "agenda:th:room" %}</th>
              <th class="text-center">{% trans "agenda:th:new_price" %}</th>
              <th class="text-center">{% trans "agenda:th:old_price" %}</th>
              <th class="text-center">{% trans "agenda:th:hotel_price" %}</th>
              <th>&nbsp;</th>
            </tr>
          </thead>
          <tbody>
            {% for price in room.day_prices|dictsort:'day' %}
              <tr>
                <td>{{ price.day|date:'d.M.Y' }}</td>
                <td>{{ price.room_type.name|default:'---' }}</td>
                <td class="text-center">{{ price.price_changed|money_format:house.currency }}</td>
                <td class="text-center">{{ price.price_original|money_format:house.currency }}</td>
                <td class="text-center">{{ price.price_accepted|money_format:house.currency }}</td>
                <td>
                  <div class="custom-control custom-switch">
                    <input type="checkbox" class="custom-control-input" id="id_price_verify_{{ price.id }}" name="price_verify" value="{{ price.id }}" checked="checked">
                    <label for="id_price_verify_{{ price.id }}" class="custom-control-label"></label>
                  </div>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>

      </div>
    {% endfor %}
  </form>
</div>